### ISSUE TITLE
Excel import in sip-creator feature

### ISSUE THREAD

**Issue by kiivihal** [delving/sip-creator#386]
Next to the current CSV import functionality it would be nice to have the ability to import directly from Excel. The following constraints should apply

* the field names should be in the header column
* the header column defines the max number of fields (fields without a header label are ignored)
* only the first worksheet is imported
* hard returns in text fields are replaced with spaces in the generated XML or placed in a separate fields

**Comment by hanswesterbeek** [comment]
Closing issues that are too old and/or unclear to current maintainers
