### ISSUE TITLE
Generating Unique URIs - Cache during mapping

### ISSUE THREAD

**Issue by geralddejong** [delving/sip-creator#404]
This could be used in a function:

    CACHE('gumby', it, {
       "$it:${_uniqueIdentifier}"
    })

It requires that this appear in generated code above:

        scriptCode.append("def CACHE = { String _cacheName, Object value, Closure generate ->\n");
        scriptCode.append("   Map ourCache = _cache[_cacheName]\n");
        scriptCode.append("   if (!ourCache) ourCache = _cache[_cacheName] = [:]\n");
        scriptCode.append("   String fetched = ourCache[value.toString()]\n");
        scriptCode.append("   if (fetched) return fetched\n");
        scriptCode.append("   ourCache[value] = generate(value)\n");
        scriptCode.append("}\n");

Also there must be this available:

        private Map<String,Map<String,String>> cache = new TreeMap<String, Map<String, String>>();

And it must be bound:

                binding.setVariable("_cache", cache);

Then these inputs:

    one
    two
    three
    four
    one
    five

produce these outputs:

    one:1000
    two:1001
    three:1002
    four:1003
    one:1000
    five:1005

Notice that the "one" entry is repeated and therefore receives the same URI.

**Comment by hanswesterbeek** [comment]
Closing issues that are too old and/or unclear to current maintainers
