### ISSUE TITLE
Java 8

### ISSUE THREAD

**Issue by geralddejong** [delving/sip-creator#478]
Sjoerd: I have been getting reports that the sip-creator for hub3 and hub2 are not working reliably under java 8. I have been testing this this morning and I can confirm this.

**Comment by hanswesterbeek** [comment]
Hi Gerald, thanks for your report.

I have been running sip-creator under JDK8 for a while and haven't had any issues.

Can you get these people to report their issue in more detail here?

**Comment by hanswesterbeek** [comment]
Closing this issue, upgrade to jdk8 has been finished.
