### ISSUE TITLE
use of red color to highlight selected/mapped field(s) is confusing as red is associated with error

### ISSUE THREAD

**Issue by zemyatin** [delving/sip-creator#482]
Light-blue would be a wiser choice. Use red only to signal error or warning.
![sip-c-mapped-fields-color](https://cloud.githubusercontent.com/assets/184673/19927643/ead22cb0-a0fa-11e6-82c2-b1259bd93c05.png)

**Comment by hanswesterbeek** [comment]
Agreed.

**Comment by hanswesterbeek** [comment]
Fixed in 709d8db8ed7
